Feat/my info
kagong-sillok/kagong-sillok-server pull request #12
Opened 2023-07-28 06:44 UTC by SonMinGyu

프론트에서 요청해주신 부분들 작업해봤습니다.
먼저 내 정보 부분이 필요하다고 해서 작업해 봤는데요, 유저 이름, 사진, 이메일, 방문일, 기록 시간 이 필요하다고 해서 Member에 사진, 방문History 필드 추가했습니다.
ArgumentResolver 구현하고 test 하는 과정에서 swagger에 jwt 추가해서 요청을 보내도록 수정했습니다. 필요없다고 판단되면 삭제해도 괜찮을 것 같습니다.
그리고 추가적으로 이미지를 여러개 한번에 생성하고 싶다고 하셔서 해당 API 추가했고,
장소Id로 리뷰 조회하는 API로 추가했습니다.
리뷰 부탁드릴게요!

2023-07-28 09:31 UTC, yxxnghwan requested changes
민규님 도메인간 참조 구조 관련해서 리뷰내용 반영 부탁드립니다!
RC 상태로 둘게요!

2023-07-28 09:31 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/member/domain/LoginHistory.java
> +    private int loginCount;
저 이거 팔로업이 안돼있어서 그런데 혹시 어떤 이유로 필요한 컬럼인가요?

2023-07-28 09:31 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/member/domain/LoginHistory.java
> +    }
파라미터를 따로 받지 않는 팩토리 메소드네요,
좀 더 적절한 이름을 붙여주는건 어떨까요? from 이라는 네이밍은 파라미터를 받을 경우에 해당 파라미터로 생성한다는 의미를 주는 것 같아요.

`init()` 같은 네이밍은 어떨까요?

2023-07-28 09:31 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/member/domain/LoginHistory.java
> +            loginCount += 1;
```suggestion
            loginCount++;
```

2023-07-28 09:31 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/member/domain/LoginHistory.java
> +    }
메소드 네이밍이 애매한 것 같아요. 날짜를 어떻게 체크하는지 호출하는 쪽에서 알 필요가 없는 메소드인가요?

`checkBeforeDate()` 이런 식으로 좀 더 친절한 메소드 네이밍을 하면 좋을 것 같아요

2023-07-28 09:31 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/member/domain/Member.java
> +    private String profileImage;
url이 들어가는 걸까요? profileImageUrl은 어떠신가요?

2023-07-28 09:31 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/member/domain/Member.java
>      }
builder 사용해서 생성자를 하나로 만들 수 있을 것 같아요

2023-07-28 09:31 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/common/config/SwaggerConfig.java
> +                .security(Arrays.asList(securityRequirement));
👍

2023-07-28 09:31 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/image/ui/ImageV1Controller.java
> +    }
한줄에 보기 어려운 것 같아요! 개행 부탁드립니다!

2023-07-28 09:31 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/image/ui/ImageV1Controller.java
> +    }
람다 코드는 메소드 참조 사용해서 줄일 수 있을 것 같고, CustomListUtil 클래스를 이용해도 좋을 것 같아요

2023-07-28 09:31 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/member/application/MemberService.java
> +    private final JwtAuthTokenProvider jwtAuthTokenProvider;
멤버쪽에서 스터디를 참조하는게 맞을까요?
특정 멤버의 스터디 기록을 불러와야하는 요구사항이라면, 멤버조회와는 분리되는게 맞을 것 같아요.
멤버가 더 루트에 가까운 도메인인 것 같고, 스터디 기록이 멤버를 참조하는 구조로 변경 부탁드립니다. 현재 구조라면 도메인간 순환참조가 일어나네요

2023-07-28 09:31 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/member/ui/MemberV1Controller.java
> +    }
안쓰이는 코드인 것 같은데 제거 부탁드려요!

2023-07-30 03:26 UTC, SonMinGyu commented on src/main/java/org/prography/kagongsillok/member/domain/LoginHistory.java
> +    private int loginCount;
내 정보에서 방문일이 필요해서 추가했습니다

2023-07-30 07:21 UTC, yxxnghwan requested changes
수정해주시느라 수고하셨습니다 민규님! 간단한 리뷰 남겼습니다!

2023-07-30 07:21 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/member/application/MemberService.java
> +    private final JwtAuthTokenProvider jwtAuthTokenProvider;
MemberService에서 JWT에 대한 의존이 존재하네요! ArgumentResolver에서 엑세스 토큰을 바로 파싱해서 memberId를 받으면 어떨까요?

2023-07-30 07:21 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/auth/application/dto/LocalJoinCommand.java
> +                .profileImageUrl(null)
굳이 넣어주지 않아도 될 것 같아요!

2023-07-30 15:51 UTC, yxxnghwan approved these changes
민규님 마이너한 의견 남겼습니다~ 이 PR은 일단 approve 할게요!

2023-07-30 15:51 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/common/resolver/AccessTokenArgumentResolver.java
> +        return new MemberIdDto(memberId);
LoginMemberDto 이런 식으로 해서 Role도 추가하면 어떨까요? 어드민용 검증이 필요할 경우도 고려해서요!

2023-07-30 15:51 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/image/application/ImageService.java
> +        return commands.stream().map(command -> command.toEntity()).collect(Collectors.toList());
메소드참조로 변환 및 개행 부탁드립니다! 스트림 코드를 한줄에 다 짜면 가독성이 많이 떨어지는 것 같아요!

2023-07-31 05:58 UTC, merged