Test/place
kagong-sillok/kagong-sillok-server pull request #2
Opened 2023-06-08 06:46 UTC by SonMinGyu

장소 인수테스트 및 application 계층, infrastructure 계층 테스트 작성해봤습니다.
부족한 부분 코멘트 남겨주세요!

2023-06-08 16:34 UTC, yxxnghwan reviewed
민규님! 수고하셨습니다!
전체적으로 코드 깔끔히 작성해주셨네요!

코멘트 남긴 부분들 확인해서 다시 리뷰요청 부탁드립니다!

2023-06-08 16:34 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/place/ui/dto/PlaceCreateRequest.java
> +        }
생성자 파라미터 갯수가 4개부터 빌더를 쓰기로 했던 것 같네요!

2023-06-08 16:34 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/place/ui/dto/PlaceCreateRequest.java
> +        }
마찬가지!

2023-06-08 16:34 UTC, yxxnghwan commented on src/test/java/org/prography/kagongsillok/acceptance/place/PlaceAcceptanceTest.java
> +    }
단건 조회일 때 조회를 여러번 해서 각각 검증하는 이유가 있을까요?

2023-06-08 16:34 UTC, yxxnghwan commented on src/test/java/org/prography/kagongsillok/acceptance/place/PlaceAcceptanceTest.java
> +    }
마찬가지인 것 같네요!

2023-06-08 16:34 UTC, yxxnghwan commented on src/test/java/org/prography/kagongsillok/acceptance/place/PlaceAcceptanceTest.java
> +        final var 장소_이름으로_검색_응답4 = 장소_이름으로_검색_요청("testPlace4");
`testPlace4` 같은 경우는 없는 이름을 요청한 것 같은데 테스트 케이스를 나눠서 작성하는건 어떨까요? 하나의 테스트에서 너무 많은 것을 검증하는 느낌입니다!

2023-06-08 16:34 UTC, yxxnghwan commented on src/test/java/org/prography/kagongsillok/acceptance/place/PlaceAcceptanceTest.java
> +    }
사이즈만 검증하기보단 검색된 결과가 검색어를 포함한 결과인지를 검증하면 해당 테스트 코드의 의도와 더 맞지 않을까 싶네요!

2023-06-08 16:36 UTC, yxxnghwan commented
추가적으로! 하나의 테스트케이스에서 너무 몰아서 검증을 하려는 듯한 느낌을 받았습니다! 테스트케이스를 따로 분리해서 검증해보면 좋을 것 같아요! 저의 경우 //when절은 최대한 가볍게 가져가는게 좋다는 생각입니다!

2023-06-09 02:00 UTC, SonMinGyu commented on src/test/java/org/prography/kagongsillok/acceptance/place/PlaceAcceptanceTest.java
> +    }
음.. 그냥 데이터가 여러 개 있을 때 잘 조회가 되나 검증해보려 했습니다.
불필요한 검증일까요?

2023-06-09 02:19 UTC, SonMinGyu commented
리뷰와 코멘트 감사합니다
말씀하신 내용 수정해서 반영해봤습니다!
추가적으로 //when을 가볍게 가져가는 느낌이 //when을 적게 가져가는 느낌으로 이해하면 될까요?

2023-06-10 05:48 UTC, yxxnghwan requested changes
추가로 코멘트 남겨봤습니다! 확인 부탁드려요!

2023-06-10 05:48 UTC, yxxnghwan commented on src/test/java/org/prography/kagongsillok/place/application/PlaceServiceTest.java
> +        List<PlaceDto> searchPlaces3 = placeService.searchPlacesByName(name3);
when절을 가볍게 가지고 가자는건 이런 부분에 해당됩니다! 같은 검증을 위한 코드가 3번이나 호출되네요! 테스트 코드의 실행시간도 생산성의 측면에서 중요합니다! 지금 이 테스트케이스의 경우 searchPlaces1, searchPlaces2, searchPlaces3을 검증하는 데에 있어 차이가 없어요! 만약 검증부의 차이가 있다면, 주어진 상황과 검증해야하는 요소가 다른 테스트이므로 따로 테스트케이스를 분리하는게 맞는 것 같네요!

2023-06-10 05:48 UTC, yxxnghwan commented on src/test/java/org/prography/kagongsillok/place/infrastructure/PlaceRepositoryImplTest.java
> +        List<Place> places5 = placeRepositoryImpl.findByNameContains(name5);
이 테스트 케이스는 테스트 케이스를 나눌 수 있을 것 같아요!

이름 전체를 입력해서 전체가 일치하는 엔티티가 검색되는 케이스랑
일부만 일치해도 검색되는 케이스랑

2023-06-10 05:48 UTC, yxxnghwan commented on hs_err_pid2332.log
이 파일은 뭘까요?

2023-06-10 05:48 UTC, yxxnghwan commented on replay_pid2332.log
얘도! 올라오지 않게 부탁드려요!

2023-06-10 06:18 UTC, SonMinGyu commented on src/test/java/org/prography/kagongsillok/place/application/PlaceServiceTest.java
> +        List<PlaceDto> searchPlaces3 = placeService.searchPlacesByName(name3);
넵 알겠습니다
같은 검증 로직을 여러번 할 필요 없다는 말씀이시군요!

2023-06-10 06:19 UTC, SonMinGyu commented on src/test/java/org/prography/kagongsillok/place/infrastructure/PlaceRepositoryImplTest.java
> +        List<Place> places5 = placeRepositoryImpl.findByNameContains(name5);
나눠서 테스트 해보겠습니다!

2023-06-10 06:19 UTC, SonMinGyu commented on hs_err_pid2332.log
.log 파일들 gitignore에 추가해서 안올라오게 수정하겠습니다.

2023-06-10 06:42 UTC, yxxnghwan reviewed
추가리뷰 남겼습니다! 확인 부탁드려요!

2023-06-10 06:42 UTC, yxxnghwan commented on src/test/java/org/prography/kagongsillok/place/infrastructure/PlaceRepositoryImplTest.java
> +}
불필요한 공백이 있네요! 인텔리제이에서 제공해주는 자동 포매팅 기능을 이용하면 작업한 파일에 대해서 편하게 공백을 정리할 수 있어요! 추가적으로 파일 마지막 줄엔 공백을 한줄 넣어주는게 좋습니다!

eof에 대해 학습해보면 좋을 것 같네요!

2023-06-10 06:42 UTC, yxxnghwan commented on src/test/java/org/prography/kagongsillok/place/application/PlaceServiceTest.java
> +        );
여기도 테스트 케이스를 나눌 수 있어보이네요! 결과가 없으면 빈 리스트가 반환되는 테스트 케이스와 일반적인 검색으로요!

2023-06-10 06:42 UTC, yxxnghwan commented on src/test/java/org/prography/kagongsillok/place/application/PlaceServiceTest.java
> +    }
👍

2023-06-10 06:42 UTC, yxxnghwan commented on src/test/java/org/prography/kagongsillok/place/infrastructure/PlaceRepositoryImplTest.java
> +        );
마찬가지입니다! 테스트케이스 더 쪼갤 수 있을 것 같아요!

2023-06-10 08:00 UTC, SonMinGyu commented
코멘트 남겨주신 부분 반영해서 테스트 수정했습니다~

2023-06-12 15:31 UTC, yxxnghwan approved these changes
수고하셨습니다!

2023-06-12 15:31 UTC, merged