Feat/review
kagong-sillok/kagong-sillok-server pull request #5
Opened 2023-06-27 08:00 UTC by SonMinGyu

review 부분 pr 요청 드립니다!
구현하면서 문제가 되었던 부분이 있는데요

Review entity안에 image와 tag를 embedded로 선언해 놓았고 image와 tag는 String을 elementCollection 타입으로 가지고 있게 했습니다. 이 부분을 LAZY 로딩 전략으로 가져가려 했는데 queryDsl에서 elementCollection 타입 join 방법을 못 찾겠어서 일단 EAGER 타입을 해 놓은 상태입니다.
그런데 또 이렇게 하니까 둘다 List로 선언했을 때 MultipleBagException이 발생해서 Set타입으로 수정해 놓은 상태입니다. 생각해보니 만약 elementCollection 타입 join 방법을 찾아서 LAZY 로딩 전략으로 가져가더라도 List 타입으로 선언하면 MultipleBagException이 발생할 것 같습니다. 이 부분을 계속 Set으로 가져가도 될지 궁금합니다!

그리고 ReviewResponse에 userNickName을 전달해줘야 하는데 merge 이후에 해당 부분 작업하려고 합니다. 이 부분 이후에 memberId로 member 조회하고 nickName 가져오는 식으로 작업하면 될지 궁금합니다!

2023-06-27 12:28 UTC, yxxnghwan requested changes
수고하셨어요 민규님! 전체적으로 잘 해주셨는데 코멘트 한번씩 확인 부탁드립니다 ㅎㅎ
테스트 코드 전체적으로 잘 짜주셔서 뿌듯하네요💪

추가적으로 정렬이나 공백, 줄바꿈 불필요한 import문 등은 인텔리제이에서 작업한 패키지나 파일 선택 후에
`커맨드 + 옵션 + L` 눌러서 자동으로 정리할 수 있습니다!

2023-06-27 12:28 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/KagongsillokApplication.java
>  public class KagongsillokApplication {
확장성을 위해 별도의 config파일에 선언하는게 좋을 것 같아요😁

2023-06-27 12:28 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/common/utils/CustomTimeFormattingUtils.java
> +    }
컨벤션상 포맷을 `yyyy-MM-dd'T'HH:mm:ss.SSS`로 사용하기로 했던 것 같아요.😁

2023-06-27 12:28 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/common/auditing/AuditingTimeEntity.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", timezone = "Asia/Seoul")
컨벤션상 포맷을 `yyyy-MM-dd'T'HH:mm:ss.SSS`로 사용하기로 했던 것 같아요.😁

2023-06-27 12:28 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/application/ReviewService.java
> +        Long reviewId = reviewUpdateCommand.getId();
컨벤션샹 지역변수에 final 붙여서 선언하기로 정했었네요!

2023-06-27 12:28 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/application/dto/ReviewCreateCommand.java
> +                .images(Images.of(imageUrls.stream().collect(Collectors.toSet())))
안에 있는건 변수나 메소드로 빼는건 어떨까요? 디미터 법칙에 대해서도 알아보아요😁

2023-06-27 12:28 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/application/dto/ReviewUpdateCommand.java
> +                .images(Images.of(imageUrls.stream().collect(Collectors.toSet())))
여기도 변수나 메소드로 빼는게 가독성 측면에서 나아보입니다!

2023-06-27 12:28 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/domain/Images.java
> +    private Set<String> images = new LinkedHashSet<>();
저희 Image 도메인이 존재하는데, 굳이 따로 ReviewImage라는 테이블을 따로 뽑으신 이유가 있을까요?
그냥 Image 엔티티의 id만 참조하면 더 가볍게 참조할 수 있어보여요

2023-06-27 12:28 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/domain/Images.java
> +        if (images.size() > 5) {
5라는 매직넘버는 어떤 값을 의미하나요? 상수로 뽑아두면 코드를 보고 의미를 파악할 수 있을 것 같네요

2023-06-27 12:28 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/application/ReviewService.java
> +    }
무슨 id로 리뷰를 여러 개 찾는걸까요? 메소드 시그니처상으론 리뷰 id를 뜻하는 것처럼 읽힙니다

2023-06-27 12:28 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/domain/Review.java
> +    }
보통 클래스 안에서 선언 순서는 다음을 지키는 것이 권장됩니다.

```
public class Foo {
    
    // fields ...
    // construcors ...
    // factory methods ...
    // other methods ...
    // getters and setters ...
    // equals and hashcode ...
    // toString
}
```

생성자가 맨 위에 있는 구조가 많이 어색하네요😅

2023-06-27 12:28 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/domain/Tags.java
> +    private Set<String> tags = new LinkedHashSet<>();
ElementCollection보단 별도의 엔티티로 추출하는건 어떨까요? 추후 특정 태그가 붙은 리뷰를 조회한다고 하면,
태그를 먼저 타고 엮인 리뷰들을 찾아야 할 것 같아서요! 태그는 엔티티가 맞을 것 같아요

2023-06-27 12:28 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/domain/exception/InvalidNumberOfImagesException.java
> +    }
5개라는 비즈니스 로직이 변경되면 하드코딩된 5라는 숫자는 어떻게 될까요?

2023-06-27 12:28 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/infrastructure/ReviewRepositoryImpl.java
> +        return queryFactory
필드 선언부와 메소드 선언부 사이엔 공백을 추가해주시면 가독성이 더 나을 것 같습니다!

2023-06-27 12:28 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/application/dto/ReviewCreateCommand.java
> +import org.prography.kagongsillok.review.domain.Tags;
사용하지 않는 import는 지워주세요!

2023-06-27 12:28 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/application/dto/ReviewDto.java
> +                )
불필요한 공백이 있는 것 같네요

2023-06-27 12:28 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/domain/Review.java
> +    private Boolean isDeleted = false;
어떤 장소에 대한 리뷰인지를 알아야 할 것 같아서 placeId가 있어야 할 것 같네요

2023-06-27 12:28 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/ui/dto/ReviewUpdateRequest.java
> +    private List<String> imageUrls;
Image 엔티티를 사용해서 내려주면 url 말고 더 많은 정보를 클라이언트에 제공해줄 수 있을 것 같아요😁

2023-06-27 12:28 UTC, yxxnghwan commented on src/test/java/org/prography/kagongsillok/acceptance/review/ReviewAcceptanceTest.java
> +                () -> assertThat(삭제후_조회한_리뷰).isEqualTo(null)
삭제후 조회한 리뷰에선 404응답을 받을 것 같은데 상태코드로 검증하는건 어떨까요?

2023-06-27 12:28 UTC, yxxnghwan commented on src/test/java/org/prography/kagongsillok/review/domain/ImageTest.java
> +        Set imageSet = new LinkedHashSet(Set.of("image1", "image2", "image3", "image4", "image5", "image6"));
```suggestion
        final Set<String> imageSet = new LinkedHashSet(Set.of("image1", "image2", "image3", "image4", "image5", "image6"));
```
제네릭 타입은 반드시 명시해주세요!

2023-06-27 12:28 UTC, yxxnghwan commented on src/test/java/org/prography/kagongsillok/review/infrastructure/ReviewRepositoryImplTest.java
> +    ReviewRepositoryImpl reviewRepositoryImpl;
이 테스트 안에서만 호출될 것 같은데 private 접근제한자 거는건 어떨까요?

2023-06-27 12:37 UTC, yxxnghwan commented
추가적으로 PR이 충돌나네요! 충돌 해결 부탁드립니다

>Review entity안에 image와 tag를 embedded로 선언해 놓았고 image와 tag는 String을 elementCollection 타입으로 가지고 있게 했습니다. 이 부분을 LAZY 로딩 전략으로 가져가려 했는데 queryDsl에서 elementCollection 타입 join 방법을 못 찾겠어서 일단 EAGER 타입을 해 놓은 상태입니다.

LAZY로딩은 조인하지 않고 해당 매핑을 호출할 때 따로 조회쿼리가 나갑니다! 조인 없이 조회하면 될겁니다! 관련해서 N + 1이 발생할 수 있는데 이 부분에 대해서도 학습해보시면 좋을 듯 합니다!

> 그리고 ReviewResponse에 userNickName을 전달해줘야 하는데 merge 이후에 해당 부분 작업하려고 합니다. 이 부분 이후에 memberId로 member 조회하고 nickName 가져오는 식으로 작업하면 될지 궁금합니다!

좋은 방법인 것 같습니다. 다만 위에서 언급한 N + 1에 대한 위험이 있는 로직이네요! in절 조건 쿼리를 활용해서 n + 1을 회피할 수 있습니다. 추후 작업하실 때 참고해보면 좋을 것 같아요💪

2023-06-27 12:51 UTC, yxxnghwan requested changes
몇개 생각나서 더 적어봤습니다..!
VO에 대해서 학습하고 적용하면 좋을 것 같아요

2023-06-27 12:51 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/domain/Review.java
> +    private int rating;
음수나 0이 들어가면 어떻게 되나요?

2023-06-27 12:51 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/domain/Review.java
> +    private String content;
최대 길이가 있을까요? 공백으로 리뷰를 등록하면 어떻게 되나요?

2023-06-28 04:52 UTC, SonMinGyu commented on src/main/java/org/prography/kagongsillok/common/utils/CustomTimeFormattingUtils.java
> +    }
figma 상에서 리뷰 불러올 때는 년.월.일 만 나오는거 같은데 시,분,초가 더 필요할까요?

2023-06-28 04:54 UTC, SonMinGyu commented on src/main/java/org/prography/kagongsillok/KagongsillokApplication.java
>  public class KagongsillokApplication {
config 파일 따로 생성하겠습니다!

2023-06-28 06:01 UTC, SonMinGyu commented on src/main/java/org/prography/kagongsillok/review/domain/Review.java
> +    }
생성자가 맨위에 있는걸로 기억했었는데 선언부 다음에 생성자가 권장되는 구조였군요! 수정하겠습니다

2023-06-30 02:32 UTC, SonMinGyu commented
수정한 내용들 push 했습니다!

2023-06-30 02:52 UTC, SonMinGyu commented
Review 인수 테스트에서 하나씩 돌리면 pass 하는데 여러개 같이 돌리면 fail이 납니다...
Tag 생성해서 넣는 것 때문에 문제가 되는 것 같은데 Tag도 API 요청으로 만든 다음에 테스트를 해야하나요..? 보통 어떤식으로 하는지 궁금합니다!

2023-06-30 15:02 UTC, yxxnghwan requested changes
민규님 수고하셨습니다!
DM으로 얘기하신 테스트 격리 잘 해결되셔서 다행입니다!

코멘트 확인 부탁드려요!
다른 부분들은 마이너한 의견이긴 한데 엔티티 설계 관해서는 도메인간 의존 방향이 전부 양방향으로 잡혀있어서 변경에 취약한 구조라 반영 부탁드립니다!

2023-06-30 15:02 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/KagongsillokApplication.java
안쓰는 임포트는 제거 부탁드립니다! 커맨드 + 옵션 + L 생활화 ㅋㅋㅋ

2023-06-30 15:02 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/ReviewTag/domain/TagReviewTags.java
> +    private List<ReviewTag> reviewTags = new ArrayList<>();
원투매니 연관관계는 하위관계일 때만 있는 것이 좋아요.
ReviewTag가 Tag엔티티의 완벽한 하위가 아닐 것 같은데 매니투원으로 가는게 어떨까요?

2023-06-30 15:02 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/ReviewTag/domain/ReviewReviewTags.java
> +    private List<ReviewTag> reviewTags = new ArrayList<>();
ReviewTag라는 네이밍이 어색할 수 있다고 생각합니다. 리뷰의 하위 도메인인 것 처럼 느껴져요.
좀 더 구체적으로 ReviewTagMapping이라는 네이밍은 어떠실까요

2023-06-30 15:02 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/ReviewTag/domain/ReviewTag.java
> +        review.getTags().getReviewTags().add(this);
디미터 법칙에 대해서 알아보는건 어떠실까요?
이렇게 꺼내서 사용하시면 일급컬렉션으로 포장하는 의미가 없어집니당..ㅎ

2023-06-30 15:02 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/ReviewTag/domain/ReviewTag.java
> +        tag.getReviews().getReviewTags().add(this);
마찬가지요!

2023-06-30 15:02 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/common/auditing/AuditingTimeEntity.java
> +    private LocalDateTime updatedAt;
시간 타입은 `ZonedDateTime` 쓰기로 했던 걸로 기억해요~!

2023-06-30 15:02 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/common/config/JpaAuditingConfig.java
> +}
👍

2023-06-30 15:02 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/application/ReviewService.java
> +    private final TagRepository tagRepository;
태그 도메인 별도일 것 같은데 TagService 따로 빼는거 어떠실까요?

2023-06-30 15:02 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/ReviewTag/domain/ReviewTag.java
> +    public void setReviewAndTag(final Review review, final Tag tag) {
set~ 으로 시작하는 메소드명은 의도를 명확하게 파악하기가 어렵습니다. 자바의 오래된 관용상 객체에 그냥 값을 넣는걸 뜻하고 안티패턴으로 분류되고 있어요. 또한 이 엔티티는 수정이 따로 일어날 일이 없는 엔티티일 것 같은데 값을 변경하는 케이스가 필요 없어보입니다

2023-06-30 15:02 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/ReviewTag/domain/ReviewTag.java
> +    private Review review;
@JoinColumn어노테이션이 빠진 것 같아요~!

2023-06-30 15:02 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/ReviewTag/domain/TagReviewTags.java
> +    private List<ReviewTag> reviewTags = new ArrayList<>();
이유는 Tag에서 이 태그가 어느 리뷰에 매핑되었는지는 알 필요가 없어서 입니다!

2023-06-30 15:02 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/application/ReviewService.java
> +            savedReviewTag.setReviewAndTag(savedReview, tag);
setter를 빼먹으면 불안정한 객체가 생성되겠네요.
생성자에서 객체를 생성하는게 좋을 것 같습니다.
더불어서 세터의 사용은 지양해주세요! 세터 자체가 안티패턴이라 ㅎㅎ

2023-06-30 15:02 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/application/dto/ReviewCreateCommand.java
> +                .tags(ReviewReviewTags.of(new ArrayList<>()))
Review 클래스 바깥에서 Review클래스의 하위모듈 일급 컬렉션을 호출할 필요가 없을 것 같네요.

일급 컬렉션의 의미에 대해서 공부해보시는건 어떨까요?

2023-06-30 15:02 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/application/dto/ReviewDto.java
> +    private String updatedAt;
String일 필요가 있을까요? ZonedDateTime이면 좋을 것 같습니다.

2023-06-30 15:02 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/application/dto/ReviewUpdateCommand.java
> +                .tags(ReviewReviewTags.of(new ArrayList<>()))
여기도 노출될 필요가 없는 클래스가 노출되는 것 같아요

2023-06-30 15:02 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/domain/Content.java
> +
vo 구현 👍

2023-06-30 15:02 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/infrastructure/ReviewRepositoryImpl.java
> +                        review.isDeleted.eq(false)
오토 박싱 비용이 발생하는 코드네요 자바에서 Boolean 객체를 미리 두개 만들어두고 사용하게 해서 생성 비용을 아껴주고 있어요.
캐싱에 대해서 알아보시면 좋을 듯 합니다!
```suggestion
                        review.isDeleted.eq(Boolean.FALSE)
```

2023-06-30 15:02 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/ui/dto/ReviewResponse.java
> +            final String updatedAt
ZonedDateTime으로 리스폰스 하시면 저희가 지정한 포맷으로 알아서 나갑니당..ㅋㅋ

2023-06-30 15:02 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/tag/application/TagService.java
> +        }
읽어오는 로직이 좀 복잡한데 쿼리안에서 isDeleted 검사해서 읽어오는건 어떠실까요?

2023-07-02 04:18 UTC, SonMinGyu commented on src/main/java/org/prography/kagongsillok/review/application/ReviewService.java
> +    private final TagRepository tagRepository;
TagService를 ReviewService에 주입해서 사용하라는 말씀이신가요?

2023-07-02 04:24 UTC, SonMinGyu commented on src/main/java/org/prography/kagongsillok/review/application/dto/ReviewCreateCommand.java
> +                .tags(ReviewReviewTags.of(new ArrayList<>()))
음 빈 생성자를 내부에서만 사용하려고 접근제어자를 사용했는데 그걸 풀고 new로 생성하는 것이 맞는걸까요?

2023-07-02 06:16 UTC, SonMinGyu commented on src/main/java/org/prography/kagongsillok/ReviewTag/domain/TagReviewTags.java
> +    private List<ReviewTag> reviewTags = new ArrayList<>();
좋은 의견 감사합니다! 말씀하신 대로 수정했습니다!

2023-07-02 06:16 UTC, SonMinGyu commented on src/main/java/org/prography/kagongsillok/review/application/dto/ReviewUpdateCommand.java
> +                .tags(ReviewReviewTags.of(new ArrayList<>()))
수정했습니다!

2023-07-02 06:34 UTC, SonMinGyu commented
코멘트 달아주신 내용을 토대로 수정 완료했습니다~!

2023-07-02 07:39 UTC, yxxnghwan reviewed
민규님 수정하시느라 고생했습니다!

리뷰 좀 더 남겨봤고 이번 리뷰내용 반영해주시면 좋겠지만, 이 PR은 너무 여러번 리뷰를 주고받은 것 같아서 원하시면 머지하시고 DM 주시면 제가 리팩토링 PR 따로 작업해서 올리도록 하겠습니다!

2023-07-02 07:39 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/ReviewTag/domain/ReviewReviewTags.java
> +public class ReviewReviewTags {
클래스명이 좀 애매한 것 같은데 ReviewTagMappings 어떠신가요?

2023-07-02 07:39 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/ReviewTag/domain/ReviewTagMapping.java
> +
👍

2023-07-02 07:39 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/ReviewTag/domain/ReviewTagMapping.java
> +    }
과한 메소드 분리라고 느껴집니다. 메소드 내부의 내용이 충분히 풀어써도 될 내용들인 것 같아요!

2023-07-02 07:39 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/ReviewTag/domain/ReviewTagMapping.java
> +    }
디미터 법칙을 준수했으면 합니다! 그리고 ReviewTag 엔티티에서 Review엔티티를 수정하는게 맞을까요?

2023-07-02 07:39 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/common/auditing/AuditingTimeEntity.java
> +    }
`@PreUpdate`와 `@LastModifiedDate` 의 호출 주기는 어떻게 다를까요?
만약 트랜잭션이 닫히기 전에 이 엔티티의 createdAt과 updatedAt을 사용해서 응답을 내리기 위한 dto를 매핑해야한다면, 어떤 어노테이션을 적용해야할까요?

2023-07-02 07:39 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/common/utils/CustomTimeFormattingUtils.java
> +    }
피그마 상에서 보여주는 형식은 view의 로직인 것 같아요. 즉 프론트엔드의 영역인 것 같네요 ㅎ..
저희는 약속된 형태의 포맷으로 일관성 있게 내려주는게 좋아보여요.
View단의 요구사항을 비즈니스를 위한 코드에 반영시키다 보면 변경에 취약한 구조가 만들어집니다!

2023-07-02 07:39 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/application/ReviewService.java
> +        }
review를 save할 때 ReviewTagMapping도 같이 save 될 수 있을 것 같은데, `@OneToMany` 어노테이션에 cascade 옵션을 설정해서 처리할 수 있습니다.

2023-07-02 07:39 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/application/ReviewService.java
> +        }
`@OneToMany` 어노테이션의 orphanRemoval 속성을 사용하면 따로 delete를 호출하지 않아도 될 것 같아요.

2023-07-02 07:39 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/application/ReviewService.java
> +        final List<ReviewTagMapping> reviewTagMappings = review.getTags().getReviewTagMappings();
이렇게 다 꺼내서 사용하면 객체지향이 깨지는 것 같네요. review에 요청할 수 있을 것 같아요.

2023-07-02 07:39 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/application/ReviewService.java
> +    private final TagRepositoryImpl tagRepositoryImpl;
왜 구체 클래스를 주입받나요?

2023-07-02 08:44 UTC, SonMinGyu commented on src/main/java/org/prography/kagongsillok/common/auditing/AuditingTimeEntity.java
> +    }
@PreUpdate는 커밋 이전에 업데이트를 하고
@LastModifiedDate는 커밋 시점에 업데이트하는걸로 알고있습니다
따라서 엔티티의 createdAt과 updatedAt을 사용해서 응답을 내리기 위한 dto를 매핑해야한다면 @PreUpdate가 더 적절할 것 같습니다

2023-07-02 09:10 UTC, yxxnghwan reviewed
민규님 고생하셨고 나머지는 제가 코드 리팩토링 PR 올리도록 할게요~!

2023-07-02 09:10 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/application/ReviewService.java
>          }
의미없는 코드가 존재하는 것 같네요

2023-07-02 09:10 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/review/domain/Review.java
> +        tags.clearReviewTagMappings();
이것도 일급컬렉션에 역할을 줄 수 있어보이네요

2023-07-02 09:10 UTC, merged