Feat/record
kagong-sillok/kagong-sillok-server pull request #8
Opened 2023-07-14 13:03 UTC by SonMinGyu

공부 기록 부분 작업해 봤습니다!
코드 리뷰 부탁 드릴게요!

2023-07-14 13:12 UTC, SonMinGyu commented
추가적으로 궁금한게 하나 있는데
service에서 각 함수에서 @Transactional을 선언해서 transaction 관리를 하는데 class 부분에 @Transactional(readOnly = true)를 쓰는 이유가 무엇인지 궁금합니다!

2023-07-15 05:00 UTC, yxxnghwan requested changes
RC 둘게요! 전체적으로 시계열로 하면 좋을 타입이 String으로 raw하게 관리되고 있어요 ㅠㅠ 수정 부탁드립니다!

2023-07-15 05:00 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/place/infrastructure/PlaceRepositoryImpl.java
> +                )
이거 전에 놓친 부분이었나보네요! 👍

2023-07-15 05:00 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/place/infrastructure/PlaceRepositoryImpl.java
> +                )
요부분 인덱스를 못탈거라 개선이 필요한데 같이 논의해보죠!

2023-07-15 05:00 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/record/application/StudyRecordService.java
> +        final Long placeId = studyRecordCreateCommand.getPlaceId();
파라마터 이름이 너무 길어요! 클래스명이나 메소드 명으로 어떤 커맨드인지 충분히 유추가 가능할 것 같은데, command로 하는건 어떨까요?

2023-07-15 05:00 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/record/application/StudyRecordService.java
> +        final List<StudyRecord> studyRecords = studyRecordRepository.findMemberRecordByMemberIdAndYearMonth(memberId, yearMonth);
year와 month는 String 타입이어야 하는 걸까요? 쿼리단에서 String으로 필요해서 String 자료형으로 지정하신 거라면, 쿼리 레벨에서 String 파라미터로 변경하시는건 어떤가요?

해당 날짜 포맷은 변경이 불가능하신걸까요? 저희는 날짜구분에선 `-`(하이픈) 쓰기로 한 것 같아요

2023-07-15 05:00 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/record/application/StudyRecordService.java
> +        final List<Long> placeIds = studyRecords.stream().map(StudyRecord::getPlaceId).collect(Collectors.toList());
줄바꿈이 있으면 좋을 것 같네요!

디미터 법칙 : 한줄에 점 하나만 찍는다

2023-07-15 05:00 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/record/domain/StudyRecord.java
> +@Table(name = "record")
테이블명은 study_record 어떠신가요?

2023-07-15 05:00 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/record/domain/vo/StudyRecordDuration.java
> +    private String value;
이게 스트링으로 저장되면 쿼리시 범위 조회는 어떻게 하나요? 시계열 타입인게 좋지 않을까요?
ZonedDateTime으로 시작시간과 종료시간을 받는게 좋을 것 같습니다

2023-07-15 05:00 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/record/domain/vo/StudyRecordDuration.java
> +    private static final int MIN_MINUTE = 0;
상수분리 👍

2023-07-15 05:00 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/record/domain/vo/StudyRecordStudyDate.java
> +    private String value;
마찬가지로 시계열 타입이 좋아보여요

2023-07-15 05:00 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/record/domain/vo/StudyRecordDuration.java
> +    }
이런 파싱 로직도 시계열 타입이면 굳이 필요가 없겠네요!

2023-07-15 05:00 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/record/domain/vo/StudyRecordStudyYearMonth.java
> +    private String value;
year와 month를 필드 분리할 수도 있겠네요.
굳이 String으로 고집할 필요가 없어보입니다 ㅠㅠ

2023-07-15 09:31 UTC, SonMinGyu commented on src/main/java/org/prography/kagongsillok/record/domain/vo/StudyRecordDuration.java
> +    private String value;
현재 앱 디자인이 공부한 시간을 받게 되어있어서 시작시간과 종료시간을 받기가 쉽지 않을 것 같습니다
제 생각에도 공부 기록을 할 때 시작시간과 종료시간을 기억하기가 쉽지 않아서..
혹시 분으로 환산해서 int로 저장하는건 어떨까요? 그러면 범위질의도 가능할 것 같습니다.

2023-07-15 12:18 UTC, SonMinGyu commented
공부 기록의 년, 월, 일을 각각 Year, Month, int 로 수정했습니다. 일을 나타내는 시계열 자료형은 없는거 같아서 일은 int로 했습니다. 그리고 Response인 studyDay는 LocalDate형으로 response하도록 했습니다.
Duration은 공부한 시간을 받는 형태이다 보니 범위 질의도 가능하도록 int로 수정했습니다.
위에서 인덱스를 못탄다는 부분은 무슨말씀인지 이해가 잘 안되어서 설명 부탁드려도 될까요?

2023-07-15 15:16 UTC, yxxnghwan requested changes
민규님 이전 리뷰 드렸던 부분중에 몇몇 부분 아직 다듬어지지 않은 것 같아서 RC 남깁니다!
수정 이후에 슬랙으로 리뷰요청 부탁드려요

2023-07-15 15:16 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/record/domain/StudyRecord.java
> +    private StudyRecordStudyDate studyDate;
다 나뉜 이유가 있을까요? LocalDate타입 or ZonedDateTime으로 관리할 수 있어보입니다!
`공부날짜` 를 의미하는 객체가 있는게 좋을 것 같아요!

2023-07-15 15:16 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/record/domain/vo/StudyRecordDescription.java
> +
👍

2023-07-15 15:16 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/record/domain/vo/StudyRecordDuration.java
> +    }
공부한 시간을 나타낸건가요? api 요청단에서부터 분 단위로 받을 수 있을 것 같습니다.
민규님 대체적으로 ui에 너무 의존적인 개발을 하고 계신 것 같아요.

2023-07-15 15:16 UTC, yxxnghwan commented on src/test/java/org/prography/kagongsillok/acceptance/AcceptanceTestFixture.java
> +                .duration("00:50")
클라이언트에서 요청할 때부터 분단위의 숫자로 입력받게 하는게 좋을 것 같아요.

2023-07-15 15:19 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/place/infrastructure/PlaceRepositoryImpl.java
> +                )
name의 경우 문자열의 타입이고 contains는 '%~~%'의 형태로 sql 조건절이 발생하게 돼요!
맨 앞에 %가 오는 경우 데이터베이스의 인덱스를 탈 수 없어서 성능이 저하될 수 있습니다.

2023-07-17 06:38 UTC, SonMinGyu commented on src/main/java/org/prography/kagongsillok/record/domain/vo/StudyRecordDuration.java
> +    }
ui에서 받고 프론트에서 처리해서 보내줄 수 있는 내용인데 너무 ui 그대로 받으려 했던 것 같네요 참고하겠습니다.

2023-07-17 08:11 UTC, SonMinGyu commented
StudyRecord에 studyDate를 LocalDate 타입으로 수정했고 Duration도 int 형으로 받는 것으로 수정했습니다.
추가로 이전에 Review에 Member 연동해야하는 것 생각나서 branch 따로 팔까 하다가 약간만 수정이 필요해서 작업해봤습니다.

2023-07-17 17:08 UTC, yxxnghwan approved these changes
민규님 작업 수고하셨습니다!
마이너한 리뷰 하나 달았는데, approve 해둘게요!
그냥 머지하셔도 되고 해당 부분 반영해서 머지하셔도 될 것 같아요!😁

2023-07-17 17:08 UTC, yxxnghwan commented on src/main/java/org/prography/kagongsillok/record/domain/vo/StudyRecordStudyDate.java
> +    }
```suggestion
    private static LocalDate validateValue(final int year, final int month, final int day) {
        try {
            return LocalDate.of(year, month, day);
        } catch (DateTimeException e) {
            throw new InvalidStudyDateException(year, month, day);
        }
    }
```

2023-07-18 07:26 UTC, merged